### ISSUE TITLE
Support for lvm

### ISSUE THREAD

**Issue by jaskaran-khurana** [canonical/encrypt-cloud-image#14]
https://learn.microsoft.com/en-us/azure/virtual-machines/linux/how-to-configure-lvm-raid-on-crypt

For lvms I am thinking we want setup similar to what this article describes, thoughts @chrisccoulson

**Comment by xnox** [comment]
Please do not use multiple forums to discuss the same thing. I.e. this issue, direct emails, meetings and salesforce case.

**Comment by jaskaran-khurana** [comment]
sure closing this as we are discussing this over email
